### ISSUE TITLE
Qwerty Keyboard Mapping Incomplete

### ISSUE THREAD

**Issue by es314159** [nicroto/viktor#33]
Is it just me or is there a missing fifth of notes right in the center when using a qwerty keyboard?

**Comment by nicroto** [comment]
Just checked the keyboard and there doesn't seem to anything wrong with it. Please elaborate a bit more on the issue you are having.

P.S. Keyboard starts at `z` (being the first C on the virtual keyboard) and then there is a second row starting at `q` (being 2 octaves up from the first C on the virtual keyboard).

**Comment by es314159** [comment]
Yes, the notes on the first row start at 'z' and go all the way to the key with '/' or '?' which is an E above the C-one octave up from the first note.  Where are F,G,A,B above this E ?  Those are the ones I can't find.  The 'q' is two octaves up from the 'z'.  That's the C above the missing FGAB.
